# Generated by Django 4.2.16 on 2024-09-27 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_patientprofile_address_patientprofile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
