# Generated by Django 4.2.16 on 2024-09-27 08:05

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_patientprofile_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialistprofile',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
