# Generated by Django 4.2.16 on 2024-09-28 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_availability_end_time_availability_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='time',
        ),
    ]
